import type { Metadata } from "next";
import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";

const inter = Noto_Sans_Georgian({
  subsets: ["georgian", "latin", "math", "symbols", "cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "PRIBS",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className="scroll-hidden">
      <body
        className={`${inter.className} relative bg-customWhite text-customPurpleDark w-full h-full`}
      >
        {children}
      </body>
    </html>
  );
}
